package com.itheima.mapper.feedback;

import com.itheima.entity.feedback.Feedback;
import com.itheima.entity.feedback.FeedbackExample;

import java.util.List;

public interface FeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String feedbackId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_feedback
     *
     * @mbg.generated
     */
    int insert(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_feedback
     *
     * @mbg.generated
     */
    int insertSelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_feedback
     *
     * @mbg.generated
     */
    List<Feedback> selectByExample(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_feedback
     *
     * @mbg.generated
     */
    Feedback selectByPrimaryKey(String feedbackId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Feedback record);
}